# Generated by Django 4.0.1 on 2022-01-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
